apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../sos-status-base/app
- ../sos-status-base/es
- ingress.yaml

patches:
- path: app-patch.yaml

namespace: $(imageName)-st