apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sosadmingui-ingress
  namespace: sosadmingui-st
  annotations:
    cert-manager.io/cluster-issuer: vault-slu.se-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 20m    
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - sosadmingui-st.wt.artdata.slu.se      
      secretName: private-star.artdata.slu.se-tls
  rules:
  - host: sosadmingui-st.wt.artdata.slu.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sosadmingui-api
            port:
              number: 5000