apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(imageName)-api
spec:
  template:
    spec:
      containers:
      - name: $(imageName)-api
        env:
        - name: AreaConfiguration
          value: '{"SwedenExtentBufferKm": 0}'
        - name: InputValaidationConfiguration
          value: |
            {
              "CountFactor": 1.1, 
              "ElasticSearchMaxRecordsInternal": 100000, 
              "ElasticSearchMaxRecordsPublic": 50000, 
              "MaxBatchSize": 1000, 
              "MaxNrElasticSearchAggregationBuckets": 65535, 
              "SignalSearchTaxonListIds": [ 1, 7, 8, 17, 18 ], 
              "TilesLimitInternal": 350000, 
              "TilesLimitPublic": 65535
            }