apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  ClientSecret: 6[>V34utc:3G
  InstrumentationKey: 0c5ee719-b2f2-4578-9a82-8bf9db41e286
  AzureSubscriptionKey: a797384f056149d2bee82a4456568fae
  BlobStorageConnectionString: DefaultEndpointsProtocol=https;AccountName=artdatastorage;AccountKey=/aXDoJGHbu77oQKd4PFl4QYM66iol6N5+xYjH1+DkMMiFl/8hpy7dpps0ou8rPSLOlGY+vSpIjUBtqmEx0smrQ==;EndpointSuffix=core.windows.net
  BlobStorageKey: /aXDoJGHbu77oQKd4PFl4QYM66iol6N5+xYjH1+DkMMiFl/8hpy7dpps0ou8rPSLOlGY+vSpIjUBtqmEx0smrQ==
  Password: M3Â£KkvX5y78p
  Salt: R@ntaRunt!0
  ProcessDbUserName: mongoadmin
  ProcessDbPassword: artdataroot
  SearchDbUserName: elastic
  SearchDbPassword: artdataroot
  SearchDbTestUserName: elastic
  SearchDbTestPassword: RgJWH7LnOXWpp8BZWTCn
  HangfireDbUserName: sos-uberuser-test
  HangfireDbPassword: LogniUMEDynCOP
  VerbatimDbUserName: sos-uberuser-test
  VerbatimDbPassword: LogniUMEDynCOP
  ApiKey: y3o0v7agqro6il4huwa3ntslhoshh7eirtvq1rot
  ApplicationId: e2ecaeec-e9eb-4ade-ab9a-2cabbe7b26c5
  AuthSecretKey: adb5434fJHNdasfgryjgvxfseedsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  AuthSecretPassword: k53mKldaefg
  RedisPassword: endastILokalUtveckling