apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sos-proxy-ingress
  namespace: sos-proxy-dev
  annotations:
    cert-manager.io/cluster-issuer: vault-slu.se-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - sos-proxy-dev.wt.artdata.slu.se
      secretName: private-star.artdata.slu.se-tls
  rules:
  - host: sos-proxy-dev.wt.artdata.slu.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sos-proxy-api
            port:
              number: 5005