apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(imageName)-web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: $(imageName)-web
        envFrom:
        - secretRef:
            name: $(imageName)-secret
        env:
        - name: ApplicationInsightsConfiguration
          value: '{"BaseAddress": "https://api.applicationinsights.io/v1", "AcceptHeaderContentType": "application/json", "InstrumentationKey": "SECRET_PLACEHOLDER", "ApiKey": "SECRET_PLACEHOLDER", "ApplicationId": "SECRET_PLACEHOLDER"}'