apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $(imageName)-es
spec:
  secretStoreRef:
    name: kubernetes-p2-artdata-css
  dataFrom:
  - extract:
      key: kv2/$(imageName)